version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"